---
# tasks file for lastdayrole
- name: get all available subsets
  na_elementsw_info:
    hostname: "{{ elementsw_hostname }}"
    username: "{{ elementsw_username }}"
    password: "{{ elementsw_password }}"
    gather_subsets: all
  register: result

- name: print cluster information
  debug: # added
   msg: "{{result}}"

block:
  - name: Add node from pending to active cluster using node IP
    tags:
    - elementsw_add_node_ip
    na_elementsw_node:
     hostname: "{{ elementsw_hostname }}"
     username: "{{ elementsw_username }}"
     password: "{{ elementsw_password }}"
     state: present
     node_id: "{{node-ids}}"
     cluster_name: sfcluster01
   register: response

   rescue:
    - name: Add node encoutered a problem
      debug: # remember to specify debug
        msg: "Error while adding the nodes to solidfire cluster"

   always: # nice use of always, printing out the response one way or another
       - name: Node add status
         debug: # remember to specify debug
           msg: "{{response}}"

- name: Add QOS Policy
  na_elementsw_qos_policy:
    hostname: "{{ elementsw_hostname }}"
    username: "{{ elementsw_username }}"
    password: "{{ elementsw_password }}"
    state: present
    name: platinum # challenge said the name was "platinum" but I'll let it slide :)
    qos: "{{policysettings}}"
