- name: Playbook - Install figlet
  hosts: planetexpress:!farnsworth   # remove farnsworth from the list of available hosts
  connection: ssh     # default is to use the connection plugin ssh.py
  gather_facts: yes   # default is yes

  tasks:
  - name: using apt to install sl and cmatrix
    apt:
        name: sl, cmatrix
    become: yes

- name: Playbook - Install sl
  hosts: farnsworth   # remove farnsworth from the list of available hosts
  connection: ssh     # default is to use the connection plugin ssh.py
  gather_facts: yes   # default is yes

  tasks:
  - name: using yum to install sl
    yum:
        name: sl
    become: yes
